export const GET_PERMISSION_LOADING = "permissions/GET_PERMISSION_LOADING";
export const GET_PERMISSION_SUCCESS = "permissions/GET_PERMISSION_SUCCESS";
export const GET_PERMISSION_FAIL = "permissions/GET_PERMISSION_FAIL";

export const UPDATE_PERMISSION_LOADING =
  "permissions/UPDATE_PERMISSION_LOADING";
export const UPDATE_PERMISSION_SUCCESS =
  "permissions/UPDATE_PERMISSION_SUCCESS";
export const UPDATE_PERMISSION_FAIL = "permissions/UPDATE_PERMISSION_FAIL";
export const UPDATE_PERMISSION_RESET = "permissions/UPDATE_PERMISSION_RESET";
