export const GET_OPERATIONTYPE_LOADING = "operations/GET_OPERATIONTYPE_LOADING";
export const GET_OPERATIONTYPE_SUCCESS = "operations/GET_OPERATIONTYPE_SUCCESS";
export const GET_OPERATIONTYPE_FAIL = "operations/GET_OPERATIONTYPE_FAIL";
