export const SET_AUTHENTICATION_LOADING = "main/SET_AUTHENTICATION_LOADING";
export const SET_AUTHENTICATION_SUCCESS = "main/SET_AUTHENTICATION_SUCCESS";
export const SET_AUTHENTICATION_FAIL = "main/SET_AUTHENTICATION_FAIL";

export const SET_ME_LOADING = "main/SET_ME_LOADING";
export const SET_ME_SUCCESS = "main/SET_ME_SUCCESS";
export const SET_ME_FAIL = "main/SET_ME_FAIL";
