export const SET_AUTHENTICATION_LOADING = "main/SET_AUTHENTICATION_LOADING";
export const SET_AUTHENTICATION_SUCCESS = "main/SET_AUTHENTICATION_SUCCESS";
export const SET_AUTHENTICATION_FAIL = "main/SET_AUTHENTICATION_FAIL";

export const SET_LOGOUT_LOADING = "main/SET_LOGOUT_LOADING";
export const SET_LOGOUT_SUCCESS = "main/SET_LOGOUT_SUCCESS";
export const SET_LOGOUT_FAIL = "main/SET_LOGOUT_FAIL";
