export const GET_ADMISSIONTYPE_LOADING = "admissions/GET_ADMISSIONTYPE_LOADING";
export const GET_ADMISSIONTYPE_SUCCESS = "admissions/GET_ADMISSIONTYPE_SUCCESS";
export const GET_ADMISSIONTYPE_FAIL = "admissions/GET_ADMISSIONTYPE_FAIL";
export const GET_ADMISSIONTYPE_SUCCESS_EMPTY =
  "admissions/GET_ADMISSIONTYPE_SUCCESS_EMPTY";
