export const CREATE_THERAPY_LOADING = "therapies/CREATE_THERAPY_LOADING";
export const CREATE_THERAPY_SUCCESS = "therapies/CREATE_THERAPY_SUCCESS";
export const CREATE_THERAPY_FAIL = "therapies/CREATE_THERAPY_FAIL";
export const CREATE_THERAPY_RESET = "therapies/CREATE_THERAPY_RESET";

export const SEARCH_THERAPY_LOADING = "therapies/SEARCH_THERAPY_LOADING";
export const SEARCH_THERAPY_SUCCESS = "therapies/SEARCH_THERAPY_SUCCESS";
export const SEARCH_THERAPY_FAIL = "therapies/SEARCH_THERAPY_FAIL";
