export const CREATE_THERAPY_LOADING = "therapies/CREATE_THERAPY_LOADING";
export const CREATE_THERAPY_SUCCESS = "therapies/CREATE_THERAPY_SUCCESS";
export const CREATE_THERAPY_FAIL = "therapies/CREATE_THERAPY_FAIL";
export const CREATE_THERAPY_RESET = "therapies/CREATE_THERAPY_RESET";

export const GET_THERAPY_LOADING = "therapies/GET_THERAPY_LOADING";
export const GET_THERAPY_SUCCESS = "therapies/GET_THERAPY_SUCCESS";
export const GET_THERAPY_FAIL = "therapies/GET_THERAPY_FAIL";
export const GET_THERAPY_SUCCESS_EMPTY = "therapies/GET_THERAPY_SUCCESS_EMPTY";
