// tslint:disable
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    GrantedAuthority,
    GrantedAuthorityFromJSON,
    GrantedAuthorityToJSON,
} from './';

/**
 * 
 * @export
 * @interface Authentication
 */
export interface Authentication {
    /**
     * 
     * @type {boolean}
     * @memberof Authentication
     */
    authenticated?: boolean;
    /**
     * 
     * @type {Array<GrantedAuthority>}
     * @memberof Authentication
     */
    authorities?: Array<GrantedAuthority>;
    /**
     * 
     * @type {object}
     * @memberof Authentication
     */
    credentials?: object;
    /**
     * 
     * @type {object}
     * @memberof Authentication
     */
    details?: object;
    /**
     * 
     * @type {string}
     * @memberof Authentication
     */
    name?: string;
    /**
     * 
     * @type {object}
     * @memberof Authentication
     */
    principal?: object;
}

export function AuthenticationFromJSON(json: any): Authentication {
    return {
        'authenticated': !exists(json, 'authenticated') ? undefined : json['authenticated'],
        'authorities': !exists(json, 'authorities') ? undefined : (json['authorities'] as Array<any>).map(GrantedAuthorityFromJSON),
        'credentials': !exists(json, 'credentials') ? undefined : json['credentials'],
        'details': !exists(json, 'details') ? undefined : json['details'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'principal': !exists(json, 'principal') ? undefined : json['principal'],
    };
}

export function AuthenticationToJSON(value?: Authentication): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'authenticated': value.authenticated,
        'authorities': value.authorities === undefined ? undefined : (value.authorities as Array<any>).map(GrantedAuthorityToJSON),
        'credentials': value.credentials,
        'details': value.details,
        'name': value.name,
        'principal': value.principal,
    };
}


