// tslint:disable
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Blob
 */
export interface Blob {
    /**
     * 
     * @type {object}
     * @memberof Blob
     */
    binaryStream?: object;
}

export function BlobFromJSON(json: any): Blob {
    return {
        'binaryStream': !exists(json, 'binaryStream') ? undefined : json['binaryStream'],
    };
}

export function BlobToJSON(value?: Blob): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'binaryStream': value.binaryStream,
    };
}


