// tslint:disable
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Dimension
 */
export interface Dimension {
    /**
     * 
     * @type {number}
     * @memberof Dimension
     */
    height?: number;
    /**
     * 
     * @type {number}
     * @memberof Dimension
     */
    width?: number;
}

export function DimensionFromJSON(json: any): Dimension {
    return {
        'height': !exists(json, 'height') ? undefined : json['height'],
        'width': !exists(json, 'width') ? undefined : json['width'],
    };
}

export function DimensionToJSON(value?: Dimension): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'height': value.height,
        'width': value.width,
    };
}


