// tslint:disable
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Rectangle,
    RectangleFromJSON,
    RectangleToJSON,
} from './';

/**
 * 
 * @export
 * @interface Rectangle2D
 */
export interface Rectangle2D {
    /**
     * 
     * @type {Rectangle}
     * @memberof Rectangle2D
     */
    bounds?: Rectangle;
    /**
     * 
     * @type {Rectangle2D}
     * @memberof Rectangle2D
     */
    bounds2D?: Rectangle2D;
    /**
     * 
     * @type {number}
     * @memberof Rectangle2D
     */
    centerX?: number;
    /**
     * 
     * @type {number}
     * @memberof Rectangle2D
     */
    centerY?: number;
    /**
     * 
     * @type {boolean}
     * @memberof Rectangle2D
     */
    empty?: boolean;
    /**
     * 
     * @type {number}
     * @memberof Rectangle2D
     */
    height?: number;
    /**
     * 
     * @type {number}
     * @memberof Rectangle2D
     */
    maxX?: number;
    /**
     * 
     * @type {number}
     * @memberof Rectangle2D
     */
    maxY?: number;
    /**
     * 
     * @type {number}
     * @memberof Rectangle2D
     */
    minX?: number;
    /**
     * 
     * @type {number}
     * @memberof Rectangle2D
     */
    minY?: number;
    /**
     * 
     * @type {Rectangle2D}
     * @memberof Rectangle2D
     */
    rect?: Rectangle2D;
    /**
     * 
     * @type {number}
     * @memberof Rectangle2D
     */
    width?: number;
    /**
     * 
     * @type {number}
     * @memberof Rectangle2D
     */
    x?: number;
    /**
     * 
     * @type {number}
     * @memberof Rectangle2D
     */
    y?: number;
}

export function Rectangle2DFromJSON(json: any): Rectangle2D {
    return {
        'bounds': !exists(json, 'bounds') ? undefined : RectangleFromJSON(json['bounds']),
        'bounds2D': !exists(json, 'bounds2D') ? undefined : Rectangle2DFromJSON(json['bounds2D']),
        'centerX': !exists(json, 'centerX') ? undefined : json['centerX'],
        'centerY': !exists(json, 'centerY') ? undefined : json['centerY'],
        'empty': !exists(json, 'empty') ? undefined : json['empty'],
        'height': !exists(json, 'height') ? undefined : json['height'],
        'maxX': !exists(json, 'maxX') ? undefined : json['maxX'],
        'maxY': !exists(json, 'maxY') ? undefined : json['maxY'],
        'minX': !exists(json, 'minX') ? undefined : json['minX'],
        'minY': !exists(json, 'minY') ? undefined : json['minY'],
        'rect': !exists(json, 'rect') ? undefined : Rectangle2DFromJSON(json['rect']),
        'width': !exists(json, 'width') ? undefined : json['width'],
        'x': !exists(json, 'x') ? undefined : json['x'],
        'y': !exists(json, 'y') ? undefined : json['y'],
    };
}

export function Rectangle2DToJSON(value?: Rectangle2D): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'bounds': RectangleToJSON(value.bounds),
        'bounds2D': Rectangle2DToJSON(value.bounds2D),
        'centerX': value.centerX,
        'centerY': value.centerY,
        'empty': value.empty,
        'height': value.height,
        'maxX': value.maxX,
        'maxY': value.maxY,
        'minX': value.minX,
        'minY': value.minY,
        'rect': Rectangle2DToJSON(value.rect),
        'width': value.width,
        'x': value.x,
        'y': value.y,
    };
}


