// tslint:disable
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Rectangle,
    RectangleFromJSON,
    RectangleToJSON,
    Rectangle2D,
    Rectangle2DFromJSON,
    Rectangle2DToJSON,
} from './';

/**
 * 
 * @export
 * @interface Shape
 */
export interface Shape {
    /**
     * 
     * @type {Rectangle}
     * @memberof Shape
     */
    bounds?: Rectangle;
    /**
     * 
     * @type {Rectangle2D}
     * @memberof Shape
     */
    bounds2D?: Rectangle2D;
}

export function ShapeFromJSON(json: any): Shape {
    return {
        'bounds': !exists(json, 'bounds') ? undefined : RectangleFromJSON(json['bounds']),
        'bounds2D': !exists(json, 'bounds2D') ? undefined : Rectangle2DFromJSON(json['bounds2D']),
    };
}

export function ShapeToJSON(value?: Shape): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'bounds': RectangleToJSON(value.bounds),
        'bounds2D': Rectangle2DToJSON(value.bounds2D),
    };
}


