export const GET_VACCINE_TYPES_LOADING =
  "vaccineTypes/GET_VACCINE_TYPES_LOADING";
export const GET_VACCINE_TYPES_SUCCESS =
  "vaccineTypes/GET_VACCINE_TYPES_SUCCESS";
export const GET_VACCINE_TYPES_FAIL = "vaccineTypes/GET_VACCINE_TYPES_FAIL";
export const GET_VACCINE_TYPES_SUCCESS_EMPTY =
  "vaccineTypes/GET_VACCINE_TYPES_SUCCESS_EMPTY";

export const CREATE_VACCINE_TYPES_LOADING =
  "vaccineTypes/CREATE_VACCINE_TYPES_LOADING";
export const CREATE_VACCINE_TYPES_SUCCESS =
  "vaccineTypes/CREATE_VACCINE_TYPES_SUCCESS";
export const CREATE_VACCINE_TYPES_FAIL =
  "vaccineTypes/CREATE_VACCINE_TYPES_FAIL";
export const CREATE_VACCINE_TYPES_RESET =
  "vaccineTypes/CREATE_VACCINE_TYPES_RESET";

export const UPDATE_VACCINE_TYPES_LOADING =
  "vaccineTypes/UPDATE_VACCINE_TYPES_LOADING";
export const UPDATE_VACCINE_TYPES_SUCCESS =
  "vaccineTypes/UPDATE_VACCINE_TYPES_SUCCESS";
export const UPDATE_VACCINE_TYPES_FAIL =
  "vaccineTypes/UPDATE_VACCINE_TYPES_FAIL";
export const UPDATE_VACCINE_TYPES_RESET =
  "vaccineTypes/UPDATE_VACCINE_TYPES_RESET";

export const DELETE_VACCINE_TYPES_LOADING =
  "vaccineTypes/DELETE_VACCINE_TYPES_LOADING";
export const DELETE_VACCINE_TYPES_SUCCESS =
  "vaccineTypes/DELETE_VACCINE_TYPES_SUCCESS";
export const DELETE_VACCINE_TYPES_FAIL =
  "vaccineTypes/DELETE_VACCINE_TYPES_FAIL";
export const DELETE_VACCINE_TYPES_RESET =
  "vaccineTypes/DELETE_VACCINE_TYPES_RESET";
