export const GET_VACCINE_TYPES_LOADING = "visits/GET_VACCINE_TYPES_LOADING";
export const GET_VACCINE_TYPES_SUCCESS = "visits/GET_VACCINE_TYPES_SUCCESS";
export const GET_VACCINE_TYPES_FAIL = "visits/GET_VACCINE_TYPES_FAIL";
export const GET_VACCINE_TYPES_SUCCESS_EMPTY =
  "visits/GET_VACCINE_TYPES_SUCCESS_EMPTY";

export const CREATE_VACCINE_TYPES_LOADING =
  "visits/CREATE_VACCINE_TYPES_LOADING";
export const CREATE_VACCINE_TYPES_SUCCESS =
  "visits/CREATE_VACCINE_TYPES_SUCCESS";
export const CREATE_VACCINE_TYPES_FAIL = "visits/CREATE_VACCINE_TYPES_FAIL";
export const CREATE_VACCINE_TYPES_RESET = "visits/CREATE_VACCINE_TYPES_RESET";

export const UPDATE_VACCINE_TYPES_LOADING =
  "visits/UPDATE_VACCINE_TYPES_LOADING";
export const UPDATE_VACCINE_TYPES_SUCCESS =
  "visits/UPDATE_VACCINE_TYPES_SUCCESS";
export const UPDATE_VACCINE_TYPES_FAIL = "visits/UPDATE_VACCINE_TYPES_FAIL";
export const UPDATE_VACCINE_TYPES_RESET = "visits/UPDATE_VACCINE_TYPES_RESET";

export const DELETE_VACCINE_TYPES_LOADING =
  "visits/DELETE_VACCINE_TYPES_LOADING";
export const DELETE_VACCINE_TYPES_SUCCESS =
  "visits/DELETE_VACCINE_TYPES_SUCCESS";
export const DELETE_VACCINE_TYPES_FAIL = "visits/DELETE_VACCINE_TYPES_FAIL";
export const DELETE_VACCINE_TYPES_RESET = "visits/DELETE_VACCINE_TYPES_RESET";
