export const CREATE_EXAMINATION_LOADING =
  "examinations/CREATE_EXAMINATION_LOADING";
export const CREATE_EXAMINATION_SUCCESS =
  "examinations/CREATE_EXAMINATION_SUCCESS";
export const CREATE_EXAMINATION_FAIL = "examinations/CREATE_EXAMINATION_FAIL";
export const CREATE_EXAMINATION_RESET = "examinations/CREATE_EXAMINATION_RESET";

export const UPDATE_EXAMINATION_LOADING =
  "examinations/UPDATE_EXAMINATION_LOADING";
export const UPDATE_EXAMINATION_SUCCESS =
  "examinations/UPDATE_EXAMINATION_SUCCESS";
export const UPDATE_EXAMINATION_FAIL = "examinations/UPDATE_EXAMINATION_FAIL";
export const UPDATE_EXAMINATION_RESET = "examinations/UPDATE_EXAMINATION_RESET";

export const GET_LAST_EXAMINATION_LOADING =
  "examinations/GET_LAST_EXAMINATION_LOADING";
export const GET_LAST_EXAMINATION_SUCCESS =
  "examinations/GET_LAST_EXAMINATION_SUCCESS";
export const GET_LAST_EXAMINATION_FAIL =
  "examinations/GET_LAST_EXAMINATION_FAIL";

export const SEARCH_EXAMINATION_LOADING =
  "examinations/SEARCH_EXAMINATION_LOADING";
export const SEARCH_EXAMINATION_SUCCESS =
  "examinations/SEARCH_EXAMINATION_SUCCESS";
export const SEARCH_EXAMINATION_FAIL = "examinations/SEARCH_EXAMINATION_FAIL";
export const SEARCH_EXAMINATION_SUCCESS_EMPTY =
  "examinations/SEARCH_EXAMINATION_SUCCESS_EMPTY";

export const DELETE_EXAMINATION_LOADING =
  "examinations/DELETE_EXAMINATION_LOADING";
export const DELETE_EXAMINATION_SUCCESS =
  "examinations/DELETE_EXAMINATION_SUCCESS";
export const DELETE_EXAMINATION_FAIL = "examinations/DELETE_EXAMINATION_FAIL";
export const DELETE_EXAMINATION_RESET = "examinations/DELETE_EXAMINATION_RESET";
