export const CREATE_EXAMINATION_LOADING =
  "examinations/CREATE_EXAMINATION_LOADING";
export const CREATE_EXAMINATION_SUCCESS =
  "examinations/CREATE_EXAMINATION_SUCCESS";
export const CREATE_EXAMINATION_FAIL = "examinations/CREATE_EXAMINATION_FAIL";
export const CREATE_EXAMINATION_RESET = "examinations/CREATE_EXAMINATION_RESET";

export const SEARCH_EXAMINATION_LOADING =
  "examinations/SEARCH_EXAMINATION_LOADING";
export const SEARCH_EXAMINATION_SUCCESS =
  "examinations/SEARCH_EXAMINATION_SUCCESS";
export const SEARCH_EXAMINATION_FAIL = "examinations/SEARCH_EXAMINATION_FAIL";
export const SEARCH_EXAMINATION_SUCCESS_EMPTY =
  "examinations/SEARCH_EXAMINATION_SUCCESS_EMPTY";
