export const GET_DISCHARGE_TYPES_LOADING =
  "dischargeTypes/GET_DISCHARGE_TYPES_LOADING";
export const GET_DISCHARGE_TYPES_SUCCESS =
  "dischargeTypes/GET_DISCHARGE_TYPES_SUCCESS";
export const GET_DISCHARGE_TYPES_FAIL =
  "dischargeTypes/GET_DISCHARGE_TYPES_FAIL";
export const GET_DISCHARGE_TYPES_SUCCESS_EMPTY =
  "dischargeTypes/GET_DISCHARGE_TYPES_SUCCESS_EMPTY";

export const CREATE_DISCHARGE_TYPES_LOADING =
  "dischargeTypes/CREATE_DISCHARGE_TYPES_LOADING";
export const CREATE_DISCHARGE_TYPES_SUCCESS =
  "dischargeTypes/CREATE_DISCHARGE_TYPES_SUCCESS";
export const CREATE_DISCHARGE_TYPES_FAIL =
  "dischargeTypes/CREATE_DISCHARGE_TYPES_FAIL";
export const CREATE_DISCHARGE_TYPES_RESET =
  "dischargeTypes/CREATE_DISCHARGE_TYPES_RESET";

export const UPDATE_DISCHARGE_TYPES_LOADING =
  "dischargeTypes/UPDATE_DISCHARGE_TYPES_LOADING";
export const UPDATE_DISCHARGE_TYPES_SUCCESS =
  "dischargeTypes/UPDATE_DISCHARGE_TYPES_SUCCESS";
export const UPDATE_DISCHARGE_TYPES_FAIL =
  "dischargeTypes/UPDATE_DISCHARGE_TYPES_FAIL";
export const UPDATE_DISCHARGE_TYPES_RESET =
  "dischargeTypes/UPDATE_DISCHARGE_TYPES_RESET";

export const DELETE_DISCHARGE_TYPES_LOADING =
  "dischargeTypes/DELETE_DISCHARGE_TYPES_LOADING";
export const DELETE_DISCHARGE_TYPES_SUCCESS =
  "dischargeTypes/DELETE_DISCHARGE_TYPES_SUCCESS";
export const DELETE_DISCHARGE_TYPES_FAIL =
  "dischargeTypes/DELETE_DISCHARGE_TYPES_FAIL";
export const DELETE_DISCHARGE_TYPES_RESET =
  "dischargeTypes/DELETE_DISCHARGE_TYPES_RESET";
