export const CREATE_ADMISSIONBOOKING_LOADING = "admissionBookings/CREATE_ADMISSIONBOOKING_LOADING";
export const CREATE_ADMISSIONBOOKING_SUCCESS = "admissionBookings/CREATE_ADMISSIONBOOKING_SUCCESS";
export const CREATE_ADMISSIONBOOKING_FAIL = "admissionBookings/CREATE_ADMISSIONBOOKING_FAIL";
export const CREATE_ADMISSIONBOOKING_RESET = "admissionBookings/CREATE_ADMISSIONBOOKING_RESET";

export const UPDATE_ADMISSIONBOOKING_LOADING = "admissionBookings/UPDATE_ADMISSIONBOOKING_LOADING";
export const UPDATE_ADMISSIONBOOKING_SUCCESS = "admissionBookings/UPDATE_ADMISSIONBOOKING_SUCCESS";
export const UPDATE_ADMISSIONBOOKING_FAIL = "admissionBookings/UPDATE_ADMISSIONBOOKING_FAIL";
export const UPDATE_ADMISSIONBOOKING_RESET = "admissionBookings/UPDATE_ADMISSIONBOOKING_RESET";

export const GET_ADMISSIONBOOKING_LOADING = "admissionBookings/GET_ADMISSIONBOOKING_LOADING";
export const GET_ADMISSIONBOOKING_SUCCESS = "admissionBookings/GET_ADMISSIONBOOKING_SUCCESS";
export const GET_ADMISSIONBOOKING_FAIL = "admissionBookings/GET_ADMISSIONBOOKING_FAIL";
export const GET_ADMISSIONBOOKING_SUCCESS_EMPTY =
  "admissionBookings/GET_ADMISSIONBOOKING_SUCCESS_EMPTY";
export const GET_CURRENT_ADMISSIONBOOKING_LOADING =
  "admissionBookings/GET_CURRENT_ADMISSIONBOOKING_LOADING";
export const GET_CURRENT_ADMISSIONBOOKING_SUCCESS =
  "admissionBookings/GET_CURRENT_ADMISSIONBOOKING_SUCCESS";
export const GET_CURRENT_ADMISSIONBOOKING_FAIL = "admissionBookings/GET_CURRENT_ADMISSIONBOOKING_FAIL";
