export const GET_LAYOUTS_LOADING = "layouts/GET_LAYOUTS_LOADING";
export const GET_LAYOUTS_SUCCESS = "layouts/GET_LAYOUTS_SUCCESS";
export const GET_LAYOUTS_SUCCESS_EMPTY = "layouts/GET_LAYOUTS_SUCCESS_EMPTY";
export const GET_LAYOUTS_FAIL = "layouts/GET_LAYOUTS_FAIL";
export const GET_LAYOUTS_RESET = "layouts/GET_LAYOUTS_RESET";

export const CREATE_LAYOUTS_LOADING = "layouts/CREATE_LAYOUTS_LOADING";
export const CREATE_LAYOUTS_SUCCESS = "layouts/CREATE_LAYOUTS_SUCCESS";
export const CREATE_LAYOUTS_FAIL = "layouts/CREATE_LAYOUTS_FAIL";
export const CREATE_LAYOUTS_RESET = "layouts/CREATE_LAB_RESET";

export const RESET_LAYOUTS_LOADING = "layouts/RESET_LAYOUTS_LOADING";
export const RESET_LAYOUTS_SUCCESS = "layouts/RESET_LAYOUTS_SUCCESS";
export const RESET_LAYOUTS_FAIL = "layouts/RESET_LAYOUTS_FAIL";
export const RESET_LAYOUTS_RESET = "layouts/RESET_LAYOUTS_RESET";
