export const GET_DISEASE_LOADING = "diseases/GET_DISEASE_LOADING";
export const GET_DISEASE_SUCCESS = "diseases/GET_DISEASE_SUCCESS";
export const GET_DISEASE_FAIL = "diseases/GET_DISEASE_FAIL";

export const GET_DISEASEIPDIN_LOADING = "diseases/GET_DISEASEIPDIN_LOADING";
export const GET_DISEASEIPDIN_SUCCESS = "diseases/GET_DISEASEIPDIN_SUCCESS";
export const GET_DISEASEIPDIN_FAIL = "diseases/GET_DISEASEIPDIN_FAIL";

export const GET_DISEASEIPDOUT_LOADING = "diseases/GET_DISEASEIPDOUT_LOADING";
export const GET_DISEASEIPDOUT_SUCCESS = "diseases/GET_DISEASEIPDOUT_SUCCESS";
export const GET_DISEASEIPDOUT_FAIL = "diseases/GET_DISEASEIPDOUT_FAIL";
