export const GET_DISEASETYPE_LOADING = "diseases/GET_DISEASETYPE_LOADING";
export const GET_DISEASETYPE_SUCCESS = "diseases/GET_DISEASETYPE_SUCCESS";
export const GET_DISEASETYPE_FAIL = "diseases/GET_DISEASETYPE_FAIL";
