export const GET_DISEASE_TYPES_LOADING =
  "diseaseTypes/GET_DISEASE_TYPES_LOADING";
export const GET_DISEASE_TYPES_SUCCESS =
  "diseaseTypes/GET_DISEASE_TYPES_SUCCESS";
export const GET_DISEASE_TYPES_FAIL = "diseaseTypes/GET_DISEASE_TYPES_FAIL";
export const GET_DISEASE_TYPES_SUCCESS_EMPTY =
  "diseaseTypes/GET_DISEASE_TYPES_SUCCESS_EMPTY";

export const CREATE_DISEASE_TYPES_LOADING =
  "diseaseTypes/CREATE_DISEASE_TYPES_LOADING";
export const CREATE_DISEASE_TYPES_SUCCESS =
  "diseaseTypes/CREATE_DISEASE_TYPES_SUCCESS";
export const CREATE_DISEASE_TYPES_FAIL =
  "diseaseTypes/CREATE_DISEASE_TYPES_FAIL";
export const CREATE_DISEASE_TYPES_RESET =
  "diseaseTypes/CREATE_DISEASE_TYPES_RESET";

export const UPDATE_DISEASE_TYPES_LOADING =
  "diseaseTypes/UPDATE_DISEASE_TYPES_LOADING";
export const UPDATE_DISEASE_TYPES_SUCCESS =
  "diseaseTypes/UPDATE_DISEASE_TYPES_SUCCESS";
export const UPDATE_DISEASE_TYPES_FAIL =
  "diseaseTypes/UPDATE_DISEASE_TYPES_FAIL";
export const UPDATE_DISEASE_TYPES_RESET =
  "diseaseTypes/UPDATE_DISEASE_TYPES_RESET";

export const DELETE_DISEASE_TYPES_LOADING =
  "diseaseTypes/DELETE_DISEASE_TYPES_LOADING";
export const DELETE_DISEASE_TYPES_SUCCESS =
  "diseaseTypes/DELETE_DISEASE_TYPES_SUCCESS";
export const DELETE_DISEASE_TYPES_FAIL =
  "diseaseTypes/DELETE_DISEASE_TYPES_FAIL";
export const DELETE_DISEASE_TYPES_RESET =
  "diseaseTypes/DELETE_DISEASE_TYPES_RESET";
