FROM node:lts

ENV PUBLIC_URL=/
ENV REACT_APP_USE_MOCK_API=
ENV REACT_APP_BASE_PATH=/

VOLUME /oh
WORKDIR /oh
COPY ../package*.json /oh
RUN npm ci --legacy-peer-deps

CMD npm start
# CMD tail -f /dev/null