export const GET_USERGROUP_LOADING = "usergroups/GET_GROUP_LOADING";
export const GET_USERGROUP_SUCCESS = "usergroups/GET_GROUP_SUCCESS";
export const GET_USERGROUP_FAIL = "usergroups/GET_GROUP_FAIL";

export const CREATE_USERGROUP_LOADING = "usergroups/CREATE_GROUP_LOADING";
export const CREATE_USERGROUP_SUCCESS = "usergroups/CREATE_GROUP_SUCCESS";
export const CREATE_USERGROUP_FAIL = "usergroups/CREATE_GROUP_FAIL";
export const CREATE_USERGROUP_RESET = "usergroups/CREATE_GROUP_RESET";

export const UPDATE_USERGROUP_LOADING = "usergroups/UPDATE_GROUP_LOADING";
export const UPDATE_USERGROUP_SUCCESS = "usergroups/UPDATE_GROUP_SUCCESS";
export const UPDATE_USERGROUP_FAIL = "usergroups/UPDATE_GROUP_FAIL";
export const UPDATE_USERGROUP_RESET = "usergroups/UPDATE_GROUP_RESET";
