export const GET_MEDICALTYPE_LOADING = "medicals/GET_MEDICALTYPE_LOADING";
export const GET_MEDICALTYPE_SUCCESS = "medicals/GET_MEDICALTYPE_SUCCESS";
export const GET_MEDICALTYPE_FAIL = "medicals/GET_MEDICALTYPE_FAIL";

export const CREATE_MEDICALTYPE_LOADING = "medicals/CREATE_MEDICALTYPE_LOADING";
export const CREATE_MEDICALTYPE_SUCCESS = "medicals/CREATE_MEDICALTYPE_SUCCESS";
export const CREATE_MEDICALTYPE_FAIL = "medicals/CREATE_MEDICALTYPE_FAIL";

export const EDIT_MEDICALTYPE_LOADING = "medicals/EDIT_MEDICALTYPE_LOADING";
export const EDIT_MEDICALTYPE_SUCCESS = "medicals/EDIT_MEDICALTYPE_SUCCESS";
export const EDIT_MEDICALTYPE_FAIL = "medicals/EDIT_MEDICALTYPE_FAIL";

export const DELETE_MEDICALTYPE_LOADING = "medicals/DELETE_MEDICALTYPE_LOADING";
export const DELETE_MEDICALTYPE_SUCCESS = "medicals/DELETE_MEDICALTYPE_SUCCESS";
export const DELETE_MEDICALTYPE_FAIL = "medicals/DELETE_MEDICALTYPE_FAIL";
