export const GET_DISCHARGETYPE_LOADING = "discharges/GET_DISCHARGETYPE_LOADING";
export const GET_DISCHARGETYPE_SUCCESS = "discharges/GET_DISCHARGETYPE_SUCCESS";
export const GET_DISCHARGETYPE_FAIL = "discharges/GET_DISCHARGETYPE_FAIL";
export const GET_DISCHARGETYPE_SUCCESS_EMPTY =
  "discharges/GET_DISCHARGETYPE_SUCCESS_EMPTY";
