export const GET_EXAM_LOADING = "exams/GET_EXAM_LOADING";
export const GET_EXAM_SUCCESS = "exams/GET_EXAM_SUCCESS";
export const GET_EXAM_FAIL = "exams/GET_EXAM_FAIL";

export const CREATE_EXAM_FAIL = "exams/CREATE_EXAM_FAIL";
export const CREATE_EXAM_LOADING = "exams/CREATE_EXAM_LOADING";
export const CREATE_EXAM_SUCCESS = "exams/CREATE_EXAM_SUCCESS";
export const CREATE_EXAM_RESET = "exams/CREATE_EXAM_RESET";

export const DELETE_EXAM_FAIL = "exams/DELETE_EXAM_FAIL";
export const DELETE_EXAM_LOADING = "exams/DELETE_EXAM_LOADING";
export const DELETE_EXAM_SUCCESS = "exams/DELETE_EXAM_SUCCESS";
export const DELETE_EXAM_RESET = "exams/DELETE_EXAM_RESET";

export const GET_EXAMROW_LOADING = "exams/GET_EXAMROW_LOADING";
export const GET_EXAMROW_SUCCESS = "exams/GET_EXAMROW_SUCCESS";
export const GET_EXAMROW_FAIL = "exams/GET_EXAMROW_FAIL";
