export const GET_SUPPLIERS_LOADING = "suppliers/GET_SUPPLIERS_LOADING";
export const GET_SUPPLIERS_SUCCESS = "suppliers/GET_SUPPLIERS_SUCCESS";
export const GET_SUPPLIERS_FAIL = "suppliers/GET_SUPPLIERS_FAIL";
