export const GET_AGE_TYPES_LOADING = "ageTypes/GET_AGE_TYPES_LOADING";
export const GET_AGE_TYPES_SUCCESS = "ageTypes/GET_AGE_TYPES_SUCCESS";
export const GET_AGE_TYPES_FAIL = "ageTypes/GET_AGE_TYPES_FAIL";
export const GET_AGE_TYPES_SUCCESS_EMPTY =
  "ageTypes/GET_AGE_TYPES_SUCCESS_EMPTY";

export const CREATE_AGE_TYPES_LOADING = "ageTypes/CREATE_AGE_TYPES_LOADING";
export const CREATE_AGE_TYPES_SUCCESS = "ageTypes/CREATE_AGE_TYPES_SUCCESS";
export const CREATE_AGE_TYPES_FAIL = "ageTypes/CREATE_AGE_TYPES_FAIL";
export const CREATE_AGE_TYPES_RESET = "ageTypes/CREATE_AGE_TYPES_RESET";

export const UPDATE_AGE_TYPES_LOADING = "ageTypes/UPDATE_AGE_TYPES_LOADING";
export const UPDATE_AGE_TYPES_SUCCESS = "ageTypes/UPDATE_AGE_TYPES_SUCCESS";
export const UPDATE_AGE_TYPES_FAIL = "ageTypes/UPDATE_AGE_TYPES_FAIL";
export const UPDATE_AGE_TYPES_RESET = "ageTypes/UPDATE_AGE_TYPES_RESET";

export const DELETE_AGE_TYPES_LOADING = "ageTypes/DELETE_AGE_TYPES_LOADING";
export const DELETE_AGE_TYPES_SUCCESS = "ageTypes/DELETE_AGE_TYPES_SUCCESS";
export const DELETE_AGE_TYPES_FAIL = "ageTypes/DELETE_AGE_TYPES_FAIL";
export const DELETE_AGE_TYPES_RESET = "ageTypes/DELETE_AGE_TYPES_RESET";
