export const CREATE_ADMISSION_LOADING = "admissions/CREATE_ADMISSION_LOADING";
export const CREATE_ADMISSION_SUCCESS = "admissions/CREATE_ADMISSION_SUCCESS";
export const CREATE_ADMISSION_FAIL = "admissions/CREATE_ADMISSION_FAIL";
export const CREATE_ADMISSION_RESET = "admissions/CREATE_ADMISSION_RESET";

export const GET_ADMISSION_LOADING = "admissions/GET_ADMISSION_LOADING";
export const GET_ADMISSION_SUCCESS = "admissions/GET_ADMISSION_SUCCESS";
export const GET_ADMISSION_FAIL = "admissions/GET_ADMISSION_FAIL";
export const GET_ADMISSION_SUCCESS_EMPTY =
  "admissions/GET_ADMISSION_SUCCESS_EMPTY";
export const GET_CURRENTADMISSION_LOADING =
  "admissions/GET_CURRENTADMISSION_LOADING";
export const GET_CURRENTADMISSION_SUCCESS =
  "admissions/GET_CURRENTADMISSION_SUCCESS";
export const GET_CURRENTADMISSION_FAIL = "admissions/GET_CURRENTADMISSION_FAIL";
