export const GET_DELIVERY_RESULT_TYPE_LOADING =
  "deliveryResultType/GET_DELIVERY_RESULT_TYPE_LOADING";
export const GET_DELIVERY_RESULT_TYPE_SUCCESS =
  "deliveryResultType/GET_DELIVERY_RESULT_TYPE_SUCCESS";
export const GET_DELIVERY_RESULT_TYPE_FAIL =
  "diseaseTypes/GET_DELIVERY_RESULT_TYPE_FAIL";
export const GET_DELIVERY_RESULT_TYPE_SUCCESS_EMPTY =
  "deliveryResultType/GET_DELIVERY_RESULT_TYPE_EMPTY";

export const CREATE_DELIVERY_RESULT_TYPE_LOADING =
  "deliveryResultType/CREATE_DELIVERY_RESULT_TYPE_LOADING";
export const CREATE_DELIVERY_RESULT_TYPE_SUCCESS =
  "deliveryResultType/CREATE_DELIVERY_RESULT_TYPE_SUCCESS";
export const CREATE_DELIVERY_RESULT_TYPE_FAIL =
  "deliveryResultType/CREATE_DELIVERY_RESULT_TYPE_FAIL";
export const CREATE_DELIVERY_RESULT_TYPE_RESET =
  "deliveryResultType/CREATE_DELIVERY_RESULT_TYPE_RESET";

export const UPDATE_DELIVERY_RESULT_TYPE_LOADING =
  "deliveryResultType/UPDATE_DELIVERY_RESULT_TYPE_LOADING";
export const UPDATE_DELIVERY_RESULT_TYPE_SUCCESS =
  "deliveryResultType/UPDATE_DELIVERY_RESULT_TYPE_SUCCESS";
export const UPDATE_DELIVERY_RESULT_TYPE_FAIL =
  "deliveryResultType/UPDATE_DELIVERY_RESULT_TYPE_FAIL";
export const UPDATE_DELIVERY_RESULT_TYPE_RESET =
  "deliveryResultType/UPDATE_DELIVERY_RESULT_TYPE_RESET";

export const DELETE_DELIVERY_RESULT_TYPE_LOADING =
  "deliveryResultType/DELETE_DELIVERY_RESULT_TYPE_LOADING";
export const DELETE_DELIVERY_RESULT_TYPE_SUCCESS =
  "deliveryResultType/DELETE_DELIVERY_RESULT_TYPE_SUCCESS";
export const DELETE_DELIVERY_RESULT_TYPE_FAIL =
  "deliveryResultType/DELETE_DELIVERY_RESULT_TYPE_FAIL";
export const DELETE_DELIVERY_RESULT_TYPE_RESET =
  "deliveryResultType/DELETE_DELIVERY_RESULT_TYPE_RESET";
