export const GET_MEDICALS_LOADING = "medicals/GET_MEDICALS_LOADING";
export const GET_MEDICALS_SUCCESS = "medicals/GET_MEDICALSSUCCESS";
export const GET_MEDICALS_FAIL = "medicals/GET_MEDICALS_FAIL";

export const GET_MEDICAL_LOADING = "medicals/GET_MEDICAL_LOADING";
export const GET_MEDICAL_SUCCESS = "medicals/GET_MEDICAL_SUCCESS";
export const GET_MEDICAL_FAIL = "medicals/GET_MEDICAL_FAIL";

export const NEW_MEDICAL_LOADING = "medicals/NEW_MEDICAL_LOADING";
export const NEW_MEDICAL_SUCCESS = "medicals/NEW_MEDICAL_SUCCESS";
export const NEW_MEDICAL_FAIL = "medicals/NEW_MEDICAL_FAIL";
export const NEW_MEDICAL_RESET = "medicals/NEW_MEDICAL_RESET";

export const EDIT_MEDICAL_LOADING = "medicals/EDIT_MEDICAL_LOADING";
export const EDIT_MEDICAL_SUCCESS = "medicals/EDIT_MEDICAL_SUCCESS";
export const EDIT_MEDICAL_FAIL = "medicals/EDIT_MEDICAL_FAIL";
export const EDIT_MEDICAL_RESET = "medicals/EDIT_MEDICAL_RESET";

export const DELETE_MEDICAL_LOADING = "medicals/DELETE_MEDICAL_LOADING";
export const DELETE_MEDICAL_SUCCESS = "medicals/DELETE_MEDICAL_SUCCESS";
export const DELETE_MEDICAL_FAIL = "medicals/DELETE_MEDICAL_FAIL";
export const DELETE_MEDICAL_RESET = "medicals/DELETE_MEDICAL_RESET";

export const EXPORT_MEDICAL_LOADING = "medicals/EXPORT_MEDICAL_LOADING";
export const EXPORT_MEDICAL_SUCCESS = "medicals/EXPORT_MEDICAL_SUCCESS";
export const EXPORT_MEDICAL_FAIL = "medicals/EXPORT_MEDICAL_FAIL";
export const EXPORT_MEDICAL_RESET = "medicals/EXPORT_MEDICAL_RESET";