export const CREATE_SURGICALRECORD_LOADING = "surgicalRecords/CREATE_SURGICALRECORD_LOADING";
export const CREATE_SURGICALRECORD_SUCCESS = "surgicalRecords/CREATE_SURGICALRECORD_SUCCESS";
export const CREATE_SURGICALRECORD_FAIL = "surgicalRecords/CREATE_SURGICALRECORD_FAIL";
export const CREATE_SURGICALRECORD_RESET = "surgicalRecords/CREATE_SURGICALRECORD_RESET";

export const UPDATE_SURGICALRECORD_LOADING = "surgicalRecords/UPDATE_SURGICALRECORD_LOADING";
export const UPDATE_SURGICALRECORD_SUCCESS = "surgicalRecords/UPDATE_SURGICALRECORD_SUCCESS";
export const UPDATE_SURGICALRECORD_FAIL = "surgicalRecords/UPDATE_SURGICALRECORD_FAIL";
export const UPDATE_SURGICALRECORD_RESET = "surgicalRecords/UPDATE_SURGICALRECORD_RESET";

export const GET_SURGICALRECORD_LOADING = "surgicalRecords/GET_SURGICALRECORD_LOADING";
export const GET_SURGICALRECORD_SUCCESS = "surgicalRecords/GET_SURGICALRECORD_SUCCESS";
export const GET_SURGICALRECORD_FAIL = "surgicalRecords/GET_SURGICALRECORD_FAIL";
export const GET_SURGICALRECORD_SUCCESS_EMPTY =
  "surgicalRecords/GET_SURGICALRECORD_SUCCESS_EMPTY";
export const GET_CURRENT_SURGICALRECORD_LOADING =
  "surgicalRecords/GET_CURRENT_SURGICALRECORD_LOADING";
export const GET_CURRENT_SURGICALRECORD_SUCCESS =
  "surgicalRecords/GET_CURRENT_SURGICALRECORD_SUCCESS";
export const GET_CURRENT_SURGICALRECORD_FAIL = "surgicalRecords/GET_CURRENT_SURGICALRECORD_FAIL";
