export const AUTH_KEY = "auth";
export const PERMISSION_KEY = "permission";
export const MOBILE_BREAKPOINT = 768;
export const TOKEN_EXPIRATION_TIMEOUT = 60000;

export const PATHS = {
  home: "/",
  login: "/login",
  patients: "/patients",
  patients_new: "/patients/new",
  patients_search: "/patients/search",
  patients_details: "/patients/details",
  patients_details_id: "/patients/details/#id",
  patients_details_edit: "/patients/details/#id/edit",
  visits: "/visits",
  laboratory: "/laboratory",
  laboratory_new: "/laboratory/new",
  laboratory_edit: "/laboratory/:id/edit",
  dashboard: "/dashboard",
  admin: "/admin",
  admin_types_base: "/admin/types",
  admin_types: "/admin/types/*",
  admin_vaccines_types: "/admin/types/vaccines",
  admin_vaccines_types_new: "/admin/types/vaccines/new",
  admin_vaccines_types_edit: "/admin/types/vaccines/:code/edit",
  admin_users: "/admin/users",
  admin_vaccines: "/admin/vaccines",
  admin_vaccines_new: "/admin/vaccines/new",
  admin_vaccines_edit: "/admin/vaccines/:code/edit",
  admin_wards: "/admin/wards",
  admin_wards_new: "/admin/wards/new",
  admin_wards_edit: "/admin/wards/:id/edit",
  admin_diseases: "/admin/diseases",
  admin_diseases_new: "/admin/diseases/new",
  admin_diseases_edit: "/admin/diseases/:id/edit",
  admin_suppliers: "/admin/suppliers",
  admin_suppliers_new: "/admin/suppliers/new",
  admin_suppliers_edit: "/admin/suppliers/:id/edit",
  admin_operations: "/admin/operations",
  admin_operations_edit: "/admin/operations/:id/edit",
  admin_operations_new: "/admin/operations/new",
  admin_admissions_types: "/admin/types/admissions",
  admin_admissions_types_new: "/admin/types/admissions/new",
  admin_admissions_types_edit: "/admin/types/admissions/:code/edit",
  admin_diseases_types: "/admin/types/diseases",
  admin_diseases_types_new: "/admin/types/diseases/new",
  admin_diseases_types_edit: "/admin/types/diseases/:code/edit",
  admin_operations_types: "/admin/types/operations",
  admin_operations_types_new: "/admin/types/operations/new",
  admin_operations_types_edit: "/admin/types/operations/:code/edit",
  admin_discharges_types: "/admin/types/discharges",
  admin_discharges_types_new: "/admin/types/discharges/new",
  admin_discharges_types_edit: "/admin/types/discharges/:code/edit",
  admin_deliveries_types: "/admin/types/deliveries",
  admin_deliveries_types_new: "/admin/types/deliveries/new",
  admin_deliveries_types_edit: "/admin/types/deliveries/:code/edit",
};
