export const AUTH_KEY = 'auth';
export const LAGUAGE_KEY = 'i18nextLng';
export const PERMISSION_KEY = 'permission';
export const MOBILE_BREAKPOINT = 768;
export const TOKEN_EXPIRATION_TIMEOUT = 60000;
export const REFRESH_TOKEN_EXPIRATION_TIMEOUT = 0;

/**
 * Maximum length the API accepts for each field, mirroring the `maxLength`
 * constraints published in `api/oh.yaml`, which in turn match the database
 * column sizes. Fields the specification does not constrain are not listed.
 */
export const FIELD_LENGTHS = {
	AdmissionDTO: { note: 65535 },
	AdmissionTypeDTO: { description: 50 },
	DeliveryResultTypeDTO: { description: 50 },
	DeliveryTypeDTO: { description: 50 },
	DischargeTypeDTO: { description: 50 },
	DiseaseDTO: { code: 10, description: 50 },
	DiseaseTypeDTO: { code: 2, description: 110 },
	ExamDTO: { code: 10, description: 100, defaultResult: 50 },
	ExamTypeDTO: { description: 50 },
	HospitalDTO: {
		description: 255,
		address: 255,
		city: 255,
		telephone: 50,
		fax: 50,
		email: 50,
		currencyCod: 3,
	},
	LaboratoryDTO: { note: 255 },
	MedicalTypeDTO: { code: 1, description: 30 },
	OpdDTO: { note: 65535, prescription: 255 },
	OperationDTO: { code: 10, description: 50 },
	OperationRowDTO: { prescriber: 150, opResult: 250, remarks: 250 },
	OperationTypeDTO: { code: 2, description: 50 },
	PatientDTO: {
		firstName: 50,
		secondName: 50,
		address: 50,
		city: 50,
		telephone: 50,
		note: 65535,
		motherName: 50,
		fatherName: 50,
		taxCode: 30,
		allergies: 255,
		anamnesis: 255,
	},
	PatientExaminationDTO: { pex_note: 2000 },
	PregnantTreatmentTypeDTO: { code: 10, description: 50 },
	SupplierDTO: {
		supName: 100,
		supAddress: 150,
		supTaxcode: 50,
		supPhone: 20,
		supFax: 20,
		supEmail: 100,
		supNote: 200,
	},
	TherapyRowDTO: { note: 65535 },
	UserDTO: { userName: 50, passwd: 50, desc: 128 },
	UserGroupDTO: { code: 50, desc: 128 },
	VaccineDTO: { code: 10, description: 50 },
	VaccineTypeDTO: { code: 1, description: 50 },
	VisitDTO: { note: 65535, service: 45 },
	WardDTO: { code: 3, description: 50, telephone: 50, fax: 50, email: 50 },
} as const;

export const PATHS = {
	home: '/',
	login: '/login',
	change_password: '/change-password',
	patients: '/patients',
	patients_new: '/patients/new',
	patients_search: '/patients/search',
	patients_details: '/patients/details',
	patients_details_id: '/patients/details/:id',
	patients_details_edit: '/patients/details/:id/edit',
	visits: '/visits',
	laboratory: '/laboratory',
	laboratory_new: '/laboratory/new',
	laboratory_edit: '/laboratory/:id/edit',
	dashboard: '/dashboard',
	admin: '/admin',
	admin_types_base: '/admin/types',
	admin_types: '/admin/types',
	admin_vaccines_types: '/admin/types/vaccines',
	admin_vaccines_types_new: '/admin/types/vaccines/new',
	admin_vaccines_types_edit: '/admin/types/vaccines/:code/edit',
	admin_users: '/admin/users',
	admin_users_new: '/admin/users/new',
	admin_usergroups_new: '/admin/users/groups/new',
	admin_usergroups_edit: '/admin/users/groups/edit/:id',
	admin_users_edit: '/admin/users/:id/edit',
	admin_vaccines: '/admin/vaccines',
	admin_vaccines_new: '/admin/vaccines/new',
	admin_vaccines_edit: '/admin/vaccines/:code/edit',
	admin_wards: '/admin/wards',
	admin_wards_new: '/admin/wards/new',
	admin_wards_edit: '/admin/wards/:id/edit',
	admin_diseases: '/admin/diseases',
	admin_diseases_new: '/admin/diseases/new',
	admin_diseases_edit: '/admin/diseases/:id/edit',
	admin_suppliers: '/admin/suppliers',
	admin_suppliers_new: '/admin/suppliers/new',
	admin_suppliers_edit: '/admin/suppliers/:id/edit',
	admin_operations: '/admin/operations',
	admin_operations_edit: '/admin/operations/:id/edit',
	admin_operations_new: '/admin/operations/new',
	admin_exams: '/admin/exams',
	admin_exams_new: '/admin/exams/new',
	admin_exams_edit: '/admin/exams/edit/:id',
	admin_exams_types: '/admin/types/exams',
	admin_exams_types_new: '/admin/types/exams/new',
	admin_exams_types_edit: '/admin/types/exams/:code/edit',
	admin_diseases_types: '/admin/types/diseases',
	admin_diseases_types_new: '/admin/types/diseases/new',
	admin_diseases_types_edit: '/admin/types/diseases/:code/edit',
	admin_operations_types: '/admin/types/operations',
	admin_operations_types_new: '/admin/types/operations/new',
	admin_operations_types_edit: '/admin/types/operations/:code/edit',
	admin_discharges_types: '/admin/types/discharges',
	admin_discharges_types_new: '/admin/types/discharges/new',
	admin_discharges_types_edit: '/admin/types/discharges/:code/edit',
	admin_deliveries_types: '/admin/types/deliveries',
	admin_deliveries_types_new: '/admin/types/deliveries/new',
	admin_deliveries_types_edit: '/admin/types/deliveries/:code/edit',
	admin_medicals_types: '/admin/types/medicals',
	admin_medicals_types_new: '/admin/types/medicals/new',
	admin_medicals_types_edit: '/admin/types/medicals/:code/edit',
	admin_pregnant_treatment_types: '/admin/types/pregnanttreatmenttypes',
	admin_pregnant_treatment_types_new: '/admin/types/pregnanttreatmenttypes/new',
	admin_pregnant_treatment_types_edit:
		'/admin/types/pregnanttreatmenttypes/:code/edit',
	admin_delivery_result_types: '/admin/types/deliveryresulttypes',
	admin_delivery_result_types_new: '/admin/types/deliveryresulttypes/new',
	admin_delivery_result_types_edit:
		'/admin/types/deliveryresulttypes/:code/edit',
	admin_admissions_types: '/admin/types/admissions',
	admin_admissions_types_new: '/admin/types/admissions/new',
	admin_admissions_types_edit: '/admin/types/admissions/:code/edit',
	admin_hospital_edit: '/admin/hospital/edit',
	admin_age_types: '/admin/types/ages',
	admin_age_types_edit: '/admin/types/ages/edit',
};
